// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finalProject_ThomasCrouch.Models;

#nullable disable

namespace CIDM3312_finalProject_ThomasCrouch.Migrations
{
    [DbContext(typeof(PrisonDbContext))]
    [Migration("20230506224151_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("finalProject_ThomasCrouch.Models.Prison", b =>
                {
                    b.Property<int>("PrisonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuardsEmployed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrisonAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrisonName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityLevel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("WardenName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.HasKey("PrisonID");

                    b.ToTable("Prisons");
                });

            modelBuilder.Entity("finalProject_ThomasCrouch.Models.Prisoner", b =>
                {
                    b.Property<int>("PrisonerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConvictedCrimes")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfRelease")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrisonID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrisonerName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.HasKey("PrisonerID");

                    b.HasIndex("PrisonID");

                    b.ToTable("Prisoners");
                });

            modelBuilder.Entity("finalProject_ThomasCrouch.Models.Prisoner", b =>
                {
                    b.HasOne("finalProject_ThomasCrouch.Models.Prison", "Prison")
                        .WithMany("Prisoners")
                        .HasForeignKey("PrisonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("finalProject_ThomasCrouch.Models.Prison", b =>
                {
                    b.Navigation("Prisoners");
                });
#pragma warning restore 612, 618
        }
    }
}
